version: '3.8'

services:
  # Vùng chứa không gian làm việc Codespaces
  codespace_env:
    image: mcr.microsoft.com/devcontainers/python:3.10
    volumes:
      - .:/workspace:cached
    network_mode: service:mongodb
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6.0
    container_name: business_os_mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7.0-alpine
    container_name: business_os_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongo_data:
  redis_data:
